version: '3.8'
services:
  app:
    container_name: bench-server
    build:
      context: ./
    ports:
      - 3333:3333
    depends_on:
      - postgres
    env_file:
      - ./.env.production

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    env_file:
      - ./.env.production
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: bench-db